# .github/workflows/deploy.yml
name: Deploy to Synology NAS

on:
  push:
    branches:
      - main

env:
  BUILD_ID: "${{ github.run_number }}-${{ github.sha }}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print build info
      run: |
        echo "Build ID: $BUILD_ID"

    - name: 🛒 Checkout code
      uses: actions/checkout@v3

    - name: 🧰 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: 📦 Install backend dependencies
      run: |
        cd backend
        npm ci

    - name: 🔨 Build backend
      run: |
        cd backend
        npm run build

    # - name: 📦 Install frontend dependencies
    #   run: |
    #     cd frontend
    #     export NG_BUILD_ID="$BUILD_ID"
    #     npm ci

    # - name: 🔨 Build frontend
    #   run: |
    #     cd frontend
    #     export BUILD_ID="$BUILD_ID"
    #     npm run build

    - name: 📂 SFTP Deploy via SSH Key
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        REMOTE_HOST: ${{ secrets.NAS_HOST }}
        REMOTE_USER: ${{ secrets.NAS_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.NAS_SSH_KEY }}
        REMOTE_PORT: 2222
        SOURCE: "frontend/dist/"
        TARGET: "/volume1/web/LaurinsSite/"