# .github/workflows/deploy.yml
name: Deploy to Synology NAS

on:
  push:
    branches:
      - main

env:
  BUILD_ID: "${{ github.run_number }}-${{ github.sha }}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print build info
      run: |
        echo "Build ID: $BUILD_ID"

    - name: 🛒 Checkout code
      uses: actions/checkout@v3

    - name: 🧰 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: 📦 Install backend dependencies
      run: |
        cd backend
        npm ci

    - name: 🔨 Build backend
      run: |
        cd backend
        npm run build

    # - name: 📦 Install frontend dependencies
    #   run: |
    #     cd frontend
    #     export NG_BUILD_ID="$BUILD_ID"
    #     npm ci

    # - name: 🔨 Build frontend
    #   run: |
    #     cd frontend
    #     export BUILD_ID="$BUILD_ID"
    #     npm run build

    # - name: Debug local frontend/dist and backend/dist content
    #   run: |
    #     ls -la backend/dist
    #     ls -la frontend/dist

    # - name: test ssh
    #   run: |
    #     echo "${{ secrets.NAS_SSH_KEY }}" > key.pem
    #     chmod 600 key.pem
    #     ssh -v -o StrictHostKeyChecking=no -i key.pem -p 2222 ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }}

    - name: 🚚 Deploy via direct rsync
      run: |
        echo "${{ secrets.NAS_SSH_KEY }}" > key.pem
        chmod 600 key.pem

        rsync -avz --progress -e "ssh -i key.pem -p 2222 -o StrictHostKeyChecking=no" backend/dist/ webdeploy@schostore.synology.me:/volume1/web/LaurinsSite

    # - name: 🔁 Restart PM2 app on NAS
    #   run: |
    #     echo "${{ secrets.NAS_SSH_KEY }}" > key.pem
    #     chmod 600 key.pem
    #     ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }} 'pm2 restart laurinsSite-backend'

      # - name: 🧹 Clean up SSH key
      #   run: rm -f key.pem